import type { DashboardStats, Device } from "@/lib/api";
const questions = ["3号宿舍楼配电箱 E03 怎么处理？", "A03 冷柜最近维修过几次？", "最近一个月牛肉采购价格是否异常？", "XX供应商延期，根据合同应该怎么处理？"];
export function Dashboard({ stats, devices }: { stats: DashboardStats; devices: Device[] }) {
  const cards = [["设备总数", stats.device_count], ["今日巡检", stats.today_inspection_count], ["待处理工单", stats.pending_maintenance_count], ["供应商", stats.supplier_count]];
  return <main className="mx-auto min-h-screen max-w-7xl px-6 py-10">
    <header className="mb-10"><div className="mb-3 inline-flex rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1 text-xs text-cyan-300">Operations Intelligence · V0.1</div><h1 className="text-4xl font-semibold tracking-tight text-white">SmartCampus <span className="text-cyan-300">AI Copilot</span></h1><p className="mt-3 text-slate-400">智慧校园运维与供应链 AI Agent 平台</p></header>
    <section className="mb-8 grid gap-4 md:grid-cols-4">{cards.map(([label,value]) => <article key={label} className="panel p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-semibold text-white">{value}</p></article>)}</section>
    <div className="grid gap-6 lg:grid-cols-[1.45fr_.8fr]">
      <section className="panel flex min-h-[500px] flex-col p-6"><div className="mb-6 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300 font-bold text-slate-950">AI</div><div><h2 className="font-medium text-white">校园智能助理</h2><p className="text-xs text-emerald-300">● 服务就绪 · 对话能力将在 V0.4 接入</p></div></div><div className="flex-1 rounded-2xl border border-dashed border-slate-700 bg-slate-950/30 p-6"><p className="max-w-lg text-sm leading-7 text-slate-400">我将能够联合查询设备、巡检、维修、采购与合同知识。当前版本已接通业务数据与基础设施健康检查。</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{questions.map(q => <button key={q} className="rounded-xl border border-slate-700 bg-slate-900/80 p-4 text-left text-sm text-slate-300 transition hover:border-cyan-400/50 hover:text-cyan-200">{q}</button>)}</div></div><div className="mt-4 flex gap-3"><input disabled placeholder="V0.4 将开放智能问答…" className="w-full rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-sm"/><button disabled className="rounded-xl bg-cyan-300 px-5 font-medium text-slate-950 opacity-60">发送</button></div></section>
      <aside className="panel p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-medium text-white">设备态势</h2><span className="text-xs text-slate-500">实时数据</span></div><div className="space-y-3">{devices.map(d => <div key={d.id} className="rounded-xl bg-slate-900/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-white">{d.device_name}</p><p className="mt-1 text-xs text-slate-500">{d.location}</p></div><span className={`mt-1 h-2.5 w-2.5 rounded-full ${d.status === "online" ? "bg-emerald-400" : d.status === "warning" ? "bg-amber-400" : "bg-rose-400"}`}/></div></div>)}</div></aside>
    </div></main>;
}

